# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [4]:
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
np.reshape(a,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [25]:
a=np.array([[0,1,2,3,4],[5,6,7,8,9],[1,1,1,1,1],[1,1,1,1,1]])
np.stack(a,axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [29]:
a=np.array([[0,1,2,3,4,1,1,1,1,1],
            [5,6,7,8,9,1,1,1,1,1]])
np.stack(a,axis=0)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [126]:
a = np.array([[1,2,3], [4,5,6],[7,8,9]])
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [99]:
a=np.array([[0,1,2,3,4],
          [5,6,7,8,9],
          [10,11,12,13,14]])
np.reshape(a,(1,15))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [100]:
a=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
np.reshape(a,(5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [60]:
a=np.random.random((5,5))
a

array([[0.23703362, 0.14707618, 0.80450129, 0.72504786, 0.00622777],
       [0.21806429, 0.10438923, 0.60870623, 0.83217265, 0.57630441],
       [0.21995662, 0.50508881, 0.19435889, 0.31591589, 0.93594293],
       [0.12423663, 0.75411084, 0.05709391, 0.59391153, 0.77743166],
       [0.85224773, 0.76313779, 0.06878728, 0.64949853, 0.95160666]])

In [61]:
np.sqrt(a)

array([[0.48686098, 0.38350513, 0.89693996, 0.85149742, 0.07891623],
       [0.46697354, 0.32309323, 0.78019627, 0.91223498, 0.75914716],
       [0.46899533, 0.710696  , 0.44086153, 0.56206396, 0.96744144],
       [0.35247217, 0.86839556, 0.23894331, 0.77065656, 0.88172085],
       [0.92317264, 0.87357758, 0.26227329, 0.80591472, 0.97550329]])

## Question:8

### Create 5x6 an array and find the mean?

In [66]:
b=np.random.random((5,6))
b

array([[0.93473488, 0.72856053, 0.21048864, 0.6850274 , 0.1262529 ,
        0.41157713],
       [0.40413718, 0.61055908, 0.4805482 , 0.16559778, 0.17065821,
        0.92389183],
       [0.30923669, 0.50328755, 0.40289071, 0.05756919, 0.23572849,
        0.92475508],
       [0.53551274, 0.89953313, 0.99086382, 0.89341453, 0.19061382,
        0.42483782],
       [0.86072922, 0.61927298, 0.67374773, 0.27981535, 0.67185528,
        0.71501917]])

In [67]:
b.mean()

0.5346905685520097

## Question:9

### Find the standard deviation of the previous array in Q8?

In [70]:
np.std(b)

0.279347823600932

## Question:10

### Find the median of the previous array in Q8?

In [71]:
np.median(b)

0.5194001442047274

## Question:11

### Find the transpose of the previous array in Q8?

In [76]:
np.transpose(b)

array([[0.93473488, 0.40413718, 0.30923669, 0.53551274, 0.86072922],
       [0.72856053, 0.61055908, 0.50328755, 0.89953313, 0.61927298],
       [0.21048864, 0.4805482 , 0.40289071, 0.99086382, 0.67374773],
       [0.6850274 , 0.16559778, 0.05756919, 0.89341453, 0.27981535],
       [0.1262529 , 0.17065821, 0.23572849, 0.19061382, 0.67185528],
       [0.41157713, 0.92389183, 0.92475508, 0.42483782, 0.71501917]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [80]:
c=np.random.random((4,4))
c

array([[0.00936705, 0.24627826, 0.78827438, 0.16219942],
       [0.95049741, 0.61476082, 0.15078569, 0.12457613],
       [0.57544864, 0.45885398, 0.19192004, 0.56404221],
       [0.27724237, 0.15203926, 0.27611137, 0.97417206]])

In [82]:
trace=np.trace(c)
print(trace)

1.7902199673415884


## Question:13

### Find the determinant of the previous array in Q12?

In [85]:
np.linalg.det(c)

0.07160131752549123

## Question:14

### Find the 5th and 95th percentile of an array?

In [92]:
a=np.array([1,2,3,4,5,6])
np.percentile(a,5)

1.25

In [90]:
np.percentile(a,95)

5.75

## Question:15

### How to find if a given array has any null values?

In [96]:
a=np.array([1,2,3,4,5,6,0,0,0,0,0,0,])
np.searchsorted(a,0)

0